@host=https://localhost:7023
@firstName=your_first_name
@lastName=your_last_name
@email=your_email@example.com
@password=your_secure_password
@accessToken=your_access_token
@ipAddress=8.8.8.8
@reportId=2

### Register
POST {{host}}/api/account/register
Content-Type: application/json

{
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login
POST {{host}}/api/account/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Generate IP report
POST {{host}}/api/reports/generate
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "ipAddress": "{{ipAddress}}"
}

### Get user's saved reports
GET {{host}}/api/reports
Authorization: Bearer {{accessToken}}
Accept: application/json

### Get report by ID
GET {{host}}/api/reports/{{reportId}}
Authorization: Bearer {{accessToken}}
Accept: application/json