@host=https://localhost:7023
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJ2bGFkaW1pcjJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJWbGFkaW1pciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL3N1cm5hbWUiOiJKYW5ldnNraSIsImp0aSI6IjQyNjVkYmJjLWY0YTAtNDBiYS1iNTY1LTQ0YzJkMzIwOTAyOSIsIm5iZiI6MTc4NDE0MjY0MywiZXhwIjoxNzg0MTQ2MjQzLCJpc3MiOiJJcEZvcmVuc2ljc1JlcG9ydC5BcGkiLCJhdWQiOiJJcEZvcmVuc2ljc1JlcG9ydC5DbGllbnQifQ.59wXcWoaa-ihP3HZ1AC1etR0eWVGm3LHEkIe7G5evos

### Register
POST {{host}}/api/account/register
Content-Type: application/json

{
  "firstName": "Vladimir",
  "lastName": "Janevski",
  "email": "vladimir2@example.com",
  "password": "SecurePassword123!"
}

### Login
POST {{host}}/api/account/login
Content-Type: application/json

{
  "email": "vladimir2@example.com",
  "password": "SecurePassword123!"
}

### Generate IP report
POST {{host}}/api/reports/generate
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "ipAddress": "8.8.8.8"
}

### Get user's saved reports
GET {{host}}/api/reports
Authorization: Bearer {{accessToken}}
Accept: application/json