@host=https://localhost:7023
//TODO: Replace all values with your own values
@firstName=Vladimir
@lastName=Janevski
@email=vladimir2@example.com
@password=SecurePassword123!
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyIiwiZW1haWwiOiJ2bGFkaW1pcjJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJWbGFkaW1pciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL3N1cm5hbWUiOiJKYW5ldnNraSIsImp0aSI6IjFkZWE5NWIzLTk0YjktNDM1Yi1hZTBhLTQzZDBkNWIyYWZlMiIsIm5iZiI6MTc4NDE4NDEwNCwiZXhwIjoxNzg0MTg3NzA0LCJpc3MiOiJJcEZvcmVuc2ljc1JlcG9ydC5BcGkiLCJhdWQiOiJJcEZvcmVuc2ljc1JlcG9ydC5DbGllbnQifQ.Z6F6xRJ-e_tO583JCUJulvO5fDwMcgQj3C3tayDnNQ0
//@ipAddress=8.8.8.8
@ipAddress=31.11.98.134
@reportId=2

### Register
POST {{host}}/api/account/register
Content-Type: application/json

{
  "firstName": "{{firstName}}",
  "lastName": "{{lastName}}",
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login
POST {{host}}/api/account/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Generate IP report
POST {{host}}/api/reports/generate
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "ipAddress": "{{ipAddress}}"
}

### Get user's saved reports
GET {{host}}/api/reports
Authorization: Bearer {{accessToken}}
Accept: application/json

### Get report by ID
GET {{host}}/api/reports/{{reportId}}
Authorization: Bearer {{accessToken}}
Accept: application/json